version: '3'

services:
  url-shortener:
    build: '.'
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      PORT: 3001
      SESSION_SECRET: CHANGEME
      MONGO_URL: "mongodb://mongodb/"
      MONGO_DB: 'URLShortener'
  mongodb:
    image: mongo:latest
    volumes:
      - "/home/erry/data2:/data/db"
    ports:
      - "127.0.0.1:27017:27017"
